## ~/.codex/config.toml（サンプル）
# 必要に応じて既存設定に追記してください。

[mcp_servers]
[mcp_servers.pinescript_mcp]
command = "node"  # 例: "C:/Program Files/nodejs/node.exe"
args = [
  "C:/path/to/pinescriptV6_MCP/pinescriptMCP/server.mjs",
  "--manual",
  "C:/path/to/pinescriptV6_MCP/pinescriptMCP/manual.json"
]

